apiVersion: rbac.authorization.k8s.io/v1

kind: RoleClusterBinding

metadata:
  name: server-read-binding

subjects:
  - kind: ServiceAccount
    name: server-read
    namespace: default

roleRef:
  - kind: RoleCluster
    name: server-read
    apiGroup: rbac.authorization.k8s.io
