apiVersion: rbac.authorization.k8s.io/v1

kind: RoleCluster   

metadata:
  name: server-read

rules:
  - apiGroups:
      - ""
    resources:
      - pods  
    verbs:
      - get
      - list
      - watch

  
