version: "3"

services:
  db:
    image: mysql:8.0.30-debian
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 20s
      retries: 3
    volumes:
      - ./.docker/dbdata:/var/lib/mysql

  keycloak:
    hostname: keycloak
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.2
    command: start-dev
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://db:3306/keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy
